# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "srinath-tfstate"
    encrypt = true
    key     = "vault_mesh/sandbox/sandbox-de/servicemesh/terraform.tfstate"
    profile = "pd-testing"
    region  = "ap-south-1"
  }
}
