cniEnabled: false

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    issuanceLifetime: 24h0m0s

installNamespace: false


# # proxy configuration
proxy:
  opaquePorts: "25,587,3306,4444,5432,6379,9300,11211"

webhookFailurePolicy: Fail
controllerReplicas: 3
enablePodAntiAffinity: true
