cniEnabled: false

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    issuanceLifetime: 24h0m0s

installNamespace: false

enablePodAntiAffinity: true

# proxy configuration
proxy:
  opaquePorts: "25,587,3306,4444,5432,6379,9300,11211"
  resources:
    cpu:
      request: 100m
    memory:
      limit: 500Mi
      request: 20Mi

# controller configuration
controllerReplicas: 3
controllerResources: &controller_resources
  cpu: &controller_resources_cpu
    limit: ""
    request: 100m
  memory:
    limit: 500Mi
    request: 50Mi
destinationResources: *controller_resources

# identity configuration
identityResources:
  cpu: *controller_resources_cpu
  memory:
    limit: 500Mi
    request: 10Mi

# heartbeat configuration
heartbeatResources: *controller_resources

# proxy injector configuration
proxyInjectorResources: *controller_resources
webhookFailurePolicy: Fail

# service profile validator configuration
spValidatorResources: *controller_resources
