# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
data "terraform_remote_state" "metacluster" {
  backend = "s3"
  config = {
    bucket  = "pandora-infra-terraform-testing"
    key     = "metacluster/sandbox-de.tfstate"
    region  = "eu-west-1"
    profile = "pd-testing"
  }
}

output "metacluster_info" {
  value = {
    metacluster_name = data.terraform_remote_state.metacluster.outputs.metacluster_name
    k8s_clusters = { for name, cluster_ep in data.terraform_remote_state.metacluster.outputs.metacluster_eks_cluster_endpoint : name =>
      {
        eks_cluster_endpoint   = cluster_ep
        k8s_host               = data.terraform_remote_state.metacluster.outputs.metacluster_eks_cluster_endpoint[name]
        cluster_ca_certificate = data.terraform_remote_state.metacluster.outputs.metacluster_eks_cluster_certificate_authority_data[name]
      }
    }
  }
}
