{{- if (hasKey .Values "csiSecretProviderClasses") }}
{{- $csiInfo := .Values.csiSecretProviderClasses }}
{{- range $csiKey, $csiVal := $csiInfo.csiSecrets }}
apiVersion: {{ default "secrets-store.csi.x-k8s.io/v1alpha1" $csiInfo.apiVersion }}
kind: SecretProviderClass
metadata:
  name: {{ $csiKey }}
  namespace: {{ $csiVal.namespace | default "default" }}
spec:
  provider: {{ $csiVal.csiProvider }}
  {{- if $csiVal.secrets.enabled }}
  secretObjects:                              
  {{- range $secret_name, $secret := $csiVal.secrets.secretData }}
  - data:
    {{- range $secret_name, $secret_kv := $secret.data }}
    - key: {{ $secret_kv }}
      objectName: {{  $secret_name }}
    {{- end }}
    secretName: {{ $secret_name }}    
    type: {{  $secret.secretType }}
  {{- end }}
  {{- end }}
  parameters:
  {{- $provider := lower $csiVal.csiProvider -}}
  {{- if eq $provider "vault" }}
    roleName: {{ $csiVal.providerInfo.roleName | quote }}
    vaultKubernetesMountPath: {{ $csiVal.providerInfo.vaultKubernetesMountPath | quote }}
    vaultAddress: {{ $csiVal.providerInfo.vaultAddress | quote }}
    objects: |
       {{- range $k, $v := $csiVal.providerInfo.objects }}
        - objectName: {{ $v.objectName | quote }}
          secretPath: {{ $v.secretPath | quote }}
          secretKey: {{ $v.secretPath | quote }}
       {{- end }}

  {{- end }}
---
{{- end }}
{{- end }}
