apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: linkerd-viz
  annotations:
    ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local:8084
    ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;      
    # ingress.kubernetes.io/auth-signin: /oauth2/sign_in
    # ingress.kubernetes.io/auth-url: https://$host/oauth2/auth

    # ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-preferred-username, authorization"
spec:
  rules:
  - host: linkerd-viz-sandbox-de-3-v121-blue.infra.works
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 8084

