# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "vault" {
  address = "https://vault-testing.infra.works/"
  token   = "s.Xqhynmx0lYT44kXnwAAhksgY"
}

provider "aws" {
  profile = "pd-testing"
  region  = "eu-west-1"
}


data "aws_eks_cluster_auth" "sandbox-de-3-v121-blue_cluster_auth" {
  name = "sandbox-de-3-v121-blue"
}

provider "kubernetes" {
  host                   = "https://2C0297ED5AA012C5318A2948D4E7D9B7.gr7.eu-west-1.eks.amazonaws.com"
  cluster_ca_certificate = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3dOakV5TVRJeU1Gb1hEVE14TURnd05ERXlNVEl5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWcyClE3dGRLcWduTExyWWxGWTdxRFhQRmwrOHZyN1pOM3NPa3lCalJyT3dMTlFzTjZzM05MUjhSdUpIOWhqc0JCN0oKaDF1N2w0TmZyTm9vOXF5MUt4SGZOMllMNHl4TEVPNXlucTdCOGxVRTRQSVNPa2pXQlN2M29IZEszSW9PRFhmeApROEpUTlQrczhxVEpheVppTlpwSjZDV0dtelVKVVh5OWhnVWw3bzdMNGpIOU8xZmg3ZExUZ1c5SHlyZlNaR3M4Cm5jNVgvczgwQzlFREgzM0Z0TDhYdHIxM2NENVp1djVieEI1dExWK1pxc2lXczc4aUpLZ1lQUWwrcjdZQ0YvTjMKOUZERkltODdsdmE3Ri8wTWNVK2xKNVUzcndvZnR1NEtQSXBFWElxWHVaTklKdjlWbUdsMEVkQWpFbklFejJkVwp2K1FtV2d1blJYby96a2NndzVjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZETXB2TEhvT1VvQUxYSXVycVp6dHdKVUlIdW1NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDOTU1bmZIeE5GSHVhbGZuNlYvVE5ZNTRIK2dkTDRQOHo4SWRZSFFWbGtlVk5TUERBMApIdGprUmRNUFVIa256RmtJTkFNQVRnQTJDNVptZVhSUEwwbVdSR3hWeVJ2WWxzL20wUjFpUE1IeWlCbWJwNVhwCmlBaitVSHN2dis5OXdlbG1KMlUzUGpKVkVGT21MQzlFVlJrRHJNQjR1TUpldUZuTGREMUpFdjdrSkRMRVU5ODUKd0FzQUpqeW13TVh2QjFCNUtmMmpsNDFnMWZvQ1VHM0p0QmhPVSs1T3NFUWJWY3d6OWI1eDJjdXZUWHV0MzV3cwovU0V4dlZwbWZLREFvMEoyaU1FdEpiTVVwUG9ya0Rock1mYW5LS2taT1RJSzFwM0xESlBjNHRPaU1WcUxnZ29NCkxrK21pczhaR0hkbTBNUDJNRUZ0aGpmQVhWdFU3Z1d1SFkwVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==")
  token                  = data.aws_eks_cluster_auth.sandbox-de-3-v121-blue_cluster_auth.token
  alias                  = "sandbox-de-3-v121-blue"
}

terraform {
  backend "s3" {
    bucket  = "srinath-tfstate"
    encrypt = true
    key     = "vault_mesh/sandbox/sandbox-de/servicemesh/terraform1.tfstate"
    profile = "pd-testing"
    region  = "ap-south-1"
  }
}
