# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

module "sandbox-de-2-v121-blue" {
  source    = "./module"
  ns = "kube-system"
  providers = {
    kubernetes = kubernetes.sandbox-de-2-v121-blue
  }
}

output sandbox-de-2-v121-blue {
  value = module.sandbox-de-2-v121-blue.op
}



module "sandbox-de-3-v121-blue" {
  source    = "./module"
  ns = "kube-system"
  providers = {
    kubernetes = kubernetes.sandbox-de-3-v121-blue
  }
}

output sandbox-de-3-v121-blue {
  value = module.sandbox-de-3-v121-blue.op
}



module "sandbox-de-4-v121-blue" {
  source    = "./module"
  ns = "kube-system"
  providers = {
    kubernetes = kubernetes.sandbox-de-4-v121-blue
  }
}

output sandbox-de-4-v121-blue {
  value = module.sandbox-de-4-v121-blue.op
}


