version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4_container2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5051:80"
    volumes:
      - .data/pgadmin-data:/var/lib/pgadmin            
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
