
#objectName - mount name in pod/secret
#secretKey - name of param in vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-user-creds
  namespace: cert-manager
spec:
  provider: vault
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
      # - key: "ca.crt"                           # data field to populate
      #   objectName: "ca.crt"     
      - key: "tls.crt"                           # data field to populate
        objectName: "tls.crt"                        # name of the mounted content to sync. this could be the object name or the object alias
      - key: "tls.key"                          
        objectName: "tls.key"                        
      secretName: linkerd-identity-trust-roots      
      type: kubernetes.io/tls 
  parameters:
    roleName: 'csi-driver-mesh-role'
    vaultKubernetesMountPath: "sandbox-de-3-v121-blue"
    vaultAddress: 'https://vault-testing.infra.works'
    objects: |
      - objectName: "tls.crt"
        secretPath: "svc-mesh-info/sandbox-de/certs/root"
        secretKey: "crt"
      - objectName: "ca.crt"
        secretPath: "svc-mesh-info/sandbox-de/certs/root"
        secretKey: "ca"        
      - objectName: "tls.key"
        secretPath: "svc-mesh-info/sandbox-de/certs/root"
        secretKey: "key"        
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cert-manager
  name: svcmesh-root-cert-sync-service-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: svcmesh-root-cert-sync-service
  labels:
    l5d-cert-type: linkerd-trust-anchor-cert-sync-service
  namespace: cert-manager
spec:
  serviceAccountName: svcmesh-root-cert-sync-service-sa
  containers:
  - name: app
    image: nginx
    env:
      - name: VAULT_ADDR
        value: "https://vault-testing.infra.works"
    volumeMounts:
      - name: 'vault-user-creds'
        mountPath: '/mnt/secrets-store'
        readOnly: true
  volumes:
    - name: vault-user-creds
      csi:
        driver: 'secrets-store.csi.k8s.io'
        readOnly: true
        volumeAttributes:
          secretProviderClass: 'vault-user-creds'
---
