apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots # this is the CM name that linkerd expects (see identity.yaml in l5d helm chart)
spec:
  sources:
  - secret:
      name: linkerd-identity-trust-roots
      key: tls.crt
  target:
    configMap:
      key: "ca-bundle.crt" # this is the CM name that linkerd expects (see identity.yaml in l5d helm chart)
    # namespaceSelector: ## this doesnt work need to check
    #   matchLabels:
    #     kubernetes.io/metadata.name: linkerd
